services:
  api:
    platform: 'linux/amd64'
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '5000:5000'
      - '8000:8000'
    image: s0ruse/m-api-v2:latest
    environment:
      - TZ=Europe/Warsaw
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - ESSA_API_URL=${ESSA_API_URL}
      - ESSA_API_KEY=${ESSA_API_KEY}
      - ESSA_API_V2_URL=${ESSA_API_V2_URL}
      - ESSA_API_KEY_V2=${ESSA_API_KEY_V2}
      - MAPI_AUTH_TOKEN=${MAPI_AUTH_TOKEN}
      - MAPI_HOSTNAME=${MAPI_HOSTNAME}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - NOTIFIER_SECRET=${NOTIFIER_SECRET}
