version: 2.0.0
services:
  api:
    platform: 'linux/amd64'
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '5000:5000'
    image: s0ruse/m-api-v2:latest
    environment:
      - TZ=Europe/Warsaw
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - ESSA_API_URL=${ESSA_API_URL}
      - ESSA_API_KEY=${ESSA_API_KEY}
